### PR TITLE
Feature update to docker

### PR DESCRIPTION
**Pull request by mosheBelostotsky**
Added dockerfile to enable dockerhub autobuild with pipeline.

### CODE REVIEW

**Comment by rqc** [comment]
@mosheBelostotsky @eitzhaki I was wondering why do we need a `Dockerfile` here? Shouldn't it be sufficient to use the image from `chatopshpe/hubot-enterprise` ? Thanks!

**Comment by mosheBelostotsky** [comment]
@rqc It's for automated builds in dockerhub.
supplements our pipeline (exactly as in hubot-enterprise)
Autobuild start once new tag pushed.
https://github.com/eedevops/hubot-enterprise/wiki/jenkins#dockerhub-autobuild

**Comment by rqc** [comment]
@mosheBelostotsky thanks, but my question is _why_ do we need it, when we already have an image built?

**Comment by rqc** [comment]
@mosheBelostotsky if you look at the history of the `dockerization` of the generator. @JonathanRosado had originally added  `Dockerfile`, which was later replaced by using a `docker-compose.yml` that would be used to run the `script` within the `chatopshpe/hubot-enterprise` container.

**Comment by mosheBelostotsky** [comment]
We need a Docker file here to make it docker image of a single integration with he thant can be uploaded to docker hub (via our pipeline and docker hub auto build)
Not only manually run via docker-compose.yml

**Comment by rqc** [comment]
OK, that would create one image per `hubot`. If that is what we want, then it is OK. thanks.

**Pull request merged**
